project_id = "qtyyiqimkysmjnaocswe"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions]
verify_jwt = true

[functions.secure-cars-api]
verify_jwt = false

[functions.secure-inspection-request]
verify_jwt = false

[functions.ssancar-scraper]
verify_jwt = false

[functions.send-inspection-notification]
verify_jwt = false

[functions.encar-sync]
verify_jwt = false

[functions.api-test]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.auctions-api]
verify_jwt = false

[functions.filters-sync]
verify_jwt = false

[functions.ai-car-search]
verify_jwt = false

[functions.cars-sync]
verify_jwt = false